plugins {
    id 'java'
}

group = 'at.helpch.papi.expansion.player'
version = '1.0.6'
description = 'PlaceholderAPI expansion for Hytale player placeholders'

repositories {
    mavenCentral()
    mavenLocal()

    maven {
        url = uri("https://maven.hytale.com/release/")
    }

    maven {
        url = uri("https://repo.helpch.at/releases")
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar()
}


dependencies {
    compileOnly("com.hypixel.hytale:Server:0.5.2")
    compileOnly("at.helpch:placeholderapi-hytale:1.0.8")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar') {
    archiveBaseName.set('PAPI-Expansion-Player')
    manifest {
        attributes(
            'Implementation-Title': project.name,
            'Implementation-Version': project.version
        )
    }
}
